---
- hosts: localhost
  connection: local
  become: true

  tasks:

## May not be needed anymore for x265 playback issues if using Totem from Flathub.

#  - name: prepare eula for ubuntu-restricted-extras 
#    debconf:
#      name: ttf-mscorefonts-installer
#      question: msttcorefonts/accepted-mscorefonts-eula
#      vtype: boolean
#      value: true
      
  - name: install packages
    package:
      name:
        - dconf-editor
        - flatpak
        - gnome-tweaks
#        - libde-x265-0
        - mc
        - python3-psutil
#        - ubuntu-restricted-extras
        - wireguard-tools

## Uninstall default Totem Video player and install Flatpak version for x265 playback
# https://gitlab.gnome.org/GNOME/totem/-/issues/526#note_1581028
# May also need libde-x265-0 package?  May NOT need ubuntu-restricted-extras (Did lots of things to try and get x265 playback working)
# Also need to remove gstreamer1.0-vaapi package as prevents videos being played both locally and smb See https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1088

  - name: Remove packages to facilitate video playback by using Totem from Flathub
    apt:
      name:
        - gstreamer1.0-vaapi
        - totem
      state: absent

## Flatpak Apps

  - name: Add the flathub flatpak repository remote to the user installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: install flatpak Apps
    flatpak:
      name: 
        - com.bitwarden.desktop
   #     - com.brave.Browser
        - com.ultimaker.cura
        - com.discordapp.Discord
        - org.signal.Signal
        - org.gnome.Totem
        - org.videolan.VLC
      state: present
      remote: flathub

  - name: Yaru GTK3 Themes
    flatpak:
      name: 
        - org.gtk.Gtk3theme.Yaru-dark
        - org.gtk.Gtk3theme.Yaru-light
        - org.gtk.Gtk3theme.Yaru-bark
        - org.gtk.Gtk3theme.Yaru-bark-dark
        - org.gtk.Gtk3theme.Yaru-magenta
        - org.gtk.Gtk3theme.Yaru-magenta-dark
        - org.gtk.Gtk3theme.Yaru-olive
        - org.gtk.Gtk3theme.Yaru-olive-dark
        - org.gtk.Gtk3theme.Yaru-prussiangreen
        - org.gtk.Gtk3theme.Yaru-prussiangreen-dark
        - org.gtk.Gtk3theme.Yaru-sage
        - org.gtk.Gtk3theme.Yaru-sage-dark   
## Not yet added to Flatpak - See:
# https://github.com/ubuntu/yaru/issues/3618
# https://github.com/flathub/flathub/pull/3053
# https://github.com/flathub/flathub/pull/3054
# https://github.com/flathub/flathub/pull/3055
# https://github.com/flathub/flathub/pull/3056
# https://github.com/flathub/flathub/pull/3059
# https://github.com/flathub/flathub/pull/3060
#        - org.gtk.Gtk3theme.Yaru-blue
#        - org.gtk.Gtk3theme.Yaru-blue
#        - org.gtk.Gtk3theme.Yaru-purple
#        - org.gtk.Gtk3theme.Yaru-purple-dark
#        - org.gtk.Gtk3theme.Yaru-red
#        - org.gtk.Gtk3theme.Yaru-red-dark
## Also relevant? https://askubuntu.com/questions/1403931/how-to-apply-system-theme-to-flatpak-apps-that-use-gtk4
      state: present
      remote: flathub
  
## Install Snaps

  - name: install snap packages
    snap:
      name:
        - authy
        - dbeaver-ce
        - gimp
        - telegram-desktop
        - vlc
        - whatsie
  
  - name: Install classic snap packages
    snap:
      name: "{{ classicsnaps }}"
      classic: yes
    vars:
      classicsnaps:
        - gitkraken

## Firefox - Setup for different profiles and also change to deb

  - name: Remove firefox snap
    snap:
      name: firefox
      state: absent

  - name: Remove Firefox "deb"
    apt:
      name:
        - firefox
      state: absent
      
  - name: Add Firefox Repository
    apt_repository:
      repo: ppa:mozillateam/ppa
      state: present

  - name: Set PPA to be higher priority
    shell:
      cmd: "printf 'Package: firefox\nPin: release o=LP-PPA-mozillateam\nPin-Priority: 1500\n' | tee /etc/apt/preferences.d/mozilla-firefox"

  - name: Update apt and install Firefox
    apt:
      name:
        - firefox
        - fonts-lyx
        - xul-ext-ubufox
      state: latest
      install_recommends: yes
#      force: yes
      update_cache: true

  - name: copy firefox desktop file
    copy:
      src: files/firefox.desktop
      dest: /home/neil/.local/share/applications/firefox.desktop
      owner: neil
      group: neil
      
  - name: copy firefox vpn desktop file
    copy:
      src: files/firefox-vpn.desktop
      dest: /home/neil/.local/share/applications/firefox-vpn.desktop
      owner: neil
      group: neil

  - name: copy firefox vpn icon
    copy:
      src: files/firefox-vpn.png
      dest: /home/neil/.local/share/applications/firefox-vpn.png
      owner: neil
      group: neil

#  - name: remove default firefox icon

## Wallpaper

  - name: copy wallpaper file
    copy:
      src: files/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg
      dest: /usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'"

  - name: set wallpaper (dark)
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'"

  - name: set wallpaper position
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

## Gnome Shell Theme

  - name: Set dark theme with blue accent
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Yaru-blue-dark'"

## Favourite Apps

  - name: Set favourite apps in Dock
    become_user: neil
    dconf:
      key: "/org/gnome/shell/favorite-apps"
      value: ['org.gnome.Nautilus.desktop', 'com.discordapp.Discord.desktop', 'telegram-desktop_telegram-desktop.desktop', 'org.signal.Signal.desktop', 'com.ultimaker.cura.desktop', 'org.gnome.TextEditor.desktop', 'org.gnome.Terminal.desktop']
      
## Dash to Dock

  - name: set icon size
    become_user: neil
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
      value: "36"

  - name: move dock to bottom
    become_user: neil
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
      value: "'BOTTOM'"
      
  - name: Change dock to not extend
    become_user: neil
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
      value: "false"

  - name: Change dock to hide
    become_user: neil
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
      value: "false"

  - name: Intellihide
    become_user: neil
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/intellihide"
      value: "true"

  - name: Don't show mounts in dock
    become_user: neil
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts"
      value: "false"
      
  - name: Don't show trash in dock
    become_user: neil
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/show-trash"
      value: "false"

## .bashrc

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/neil/.bashrc
      owner: neil
      group: neil

## Automate ansible deployment via cron

#  - name: add  ansible user
#    user:
#      name: ansible
#      system: yes

#  - name: set up sudo for ansible user
#    copy:
#      src: files/sudoer_ansible
#      dest: /etc/sudoers.d/ansible
#      owner: root
#      group: root
#      mode: 0440

#  - name: add ansible-pull cron job
#    cron:
#      name: ansible auto-provision
#      user: ansible
#      minute: "*/10"
#      job: ansible-pull -o -U https://github.com/argoncoast/ansible_desktop.git 

## Install Docker & Docker-Compose

#  - name: Install required system packages
#    apt:
#      pkg:
#        - apt-transport-https
#        - ca-certificates
#        - curl
#        - software-properties-common
#        - python3-pip
#        - virtualenv
#        - python3-setuptools
#      state: latest
#      update_cache: true

#  - name: Add Docker GPG apt Key
#    get_url:
#      url: https://download.docker.com/linux/ubuntu/gpg
#      dest: /etc/apt/trusted.gpg.d/docker.asc
#      state: present

#  - name: Add Docker Repository
#    apt_repository:
#      repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu kinetic stable
#      state: present

#  - name: Update apt and install docker-ce
#    apt:
#      name: 
#        - docker-ce
#        - docker-compose-plugin
#      state: latest
#      update_cache: true

## To-do - Run docker daemon and add user to docker group.

## Install Brave

  - name: Add Brave GPG apt Key
    get_url:
      url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      dest: /etc/apt/trusted.gpg.d/brave.asc
    become: true

  - name: Add Brave Repository
    apt_repository:
      repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/brave.asc] https://brave-browser-apt-release.s3.brave.com/ stable main
      state: present

  - name: Update apt and install Brave
    apt:
      name: 
        - brave-browser
      state: latest
      update_cache: true
    
