---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - flatpak
        - mc
        - python3-psutil
        
  - name: Add the flathub flatpak repository remote to the user installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  
  - name: Yaru GTK3 Themes
    flatpak:
      name: 
        - org.gtk.Gtk3theme.Yaru-dark
        - org.gtk.Gtk3theme.Yaru-light
        - org.gtk.Gtk3theme.Yaru-bark
        - org.gtk.Gtk3theme.Yaru-bark-dark
        - org.gtk.Gtk3theme.Yaru-magenta
        - org.gtk.Gtk3theme.Yaru-magenta-dark
        - org.gtk.Gtk3theme.Yaru-olive
        - org.gtk.Gtk3theme.Yaru-olive-dark
        - org.gtk.Gtk3theme.Yaru-prussiangreen
        - org.gtk.Gtk3theme.Yaru-prussiangreen-dark
        - org.gtk.Gtk3theme.Yaru-sage
        - org.gtk.Gtk3theme.Yaru-sage-dark
        - org.gtk.Gtk3theme.Yaru-Amber
        - org.gtk.Gtk3theme.Yaru-Amber-dark
        - org.gtk.Gtk3theme.Yaru-Amber-light
        - org.gtk.Gtk3theme.Yaru-Aqua
        - org.gtk.Gtk3theme.Yaru-Aqua-dark
        - org.gtk.Gtk3theme.Yaru-Aqua-light
        - org.gtk.Gtk3theme.Yaru-Aubergine
        - org.gtk.Gtk3theme.Yaru-Aubergine-dark
        - org.gtk.Gtk3theme.Yaru-Aubergine-light
        - org.gtk.Gtk3theme.Yaru-Blue
        - org.gtk.Gtk3theme.Yaru-Blue-dark
        - org.gtk.Gtk3theme.Yaru-Blue-light
        - org.gtk.Gtk3theme.Yaru-Brown
        - org.gtk.Gtk3theme.Yaru-Brown-dark
        - org.gtk.Gtk3theme.Yaru-Brown-light
        - org.gtk.Gtk3theme.Yaru-Cinnamon
        - org.gtk.Gtk3theme.Yaru-Cinnamon-dark
        - org.gtk.Gtk3theme.Yaru-Cinnamon-light
        - org.gtk.Gtk3theme.Yaru-Deepblue
        - org.gtk.Gtk3theme.Yaru-Deepblue-dark
        - org.gtk.Gtk3theme.Yaru-Deepblue-light
        - org.gtk.Gtk3theme.Yaru-Green
        - org.gtk.Gtk3theme.Yaru-Green-dark
        - org.gtk.Gtk3theme.Yaru-Green-light
        - org.gtk.Gtk3theme.Yaru-Grey
        - org.gtk.Gtk3theme.Yaru-Grey-dark
        - org.gtk.Gtk3theme.Yaru-Grey-light
        - org.gtk.Gtk3theme.Yaru-Lavender
        - org.gtk.Gtk3theme.Yaru-Lavender-dark
        - org.gtk.Gtk3theme.Yaru-Lavender-light
        - org.gtk.Gtk3theme.Yaru-MATE
        - org.gtk.Gtk3theme.Yaru-MATE-dark
        - org.gtk.Gtk3theme.Yaru-MATE-light
        - org.gtk.Gtk3theme.Yaru-Orange
        - org.gtk.Gtk3theme.Yaru-Orange-dark
        - org.gtk.Gtk3theme.Yaru-Orange-light
        - org.gtk.Gtk3theme.Yaru-Pink
        - org.gtk.Gtk3theme.Yaru-Pink-dark
        - org.gtk.Gtk3theme.Yaru-Pink-light
        - org.gtk.Gtk3theme.Yaru-Purple
        - org.gtk.Gtk3theme.Yaru-Purple-dark
        - org.gtk.Gtk3theme.Yaru-Purple-light
        - org.gtk.Gtk3theme.Yaru-Red
        - org.gtk.Gtk3theme.Yaru-Red-dark
        - org.gtk.Gtk3theme.Yaru-Red-light
        - org.gtk.Gtk3theme.Yaru-remix
        - org.gtk.Gtk3theme.Yaru-remix-dark
        - org.gtk.Gtk3theme.Yaru-remix-light
        - org.gtk.Gtk3theme.Yaru-Teal
        - org.gtk.Gtk3theme.Yaru-Teal-dark
        - org.gtk.Gtk3theme.Yaru-Teal-light
        - org.gtk.Gtk3theme.Yaru-Yellow
        - org.gtk.Gtk3theme.Yaru-Yellow-dark
        - org.gtk.Gtk3theme.Yaru-Yellow-light
      state: present
      remote: flathub

  - name: Bitwarden
    flatpak:
      name: com.bitwarden.desktop
      state: present
      remote: flathub

  - name: Cura
    flatpak:
      name: com.ultimaker.cura
      state: present
      remote: flathub
      
  - name: Discord
    flatpak:
      name: com.discordapp.Discord
      state: present
      remote: flathub
  
  - name: VLC
    flatpak:
      name: org.videolan.VLC
      state: present
      remote: flathub
      
  - name: install snap packages
    snap:
      name:
        - authy
        - dbeaver-ce
        - gimp
        - whatsie
  
  - name: Install classic snap packages
    snap:
      name: "{{ classicsnaps }}"
      classic: yes
    vars:
      classicsnaps:
        - gitkraken

  - name: copy firefox vpn icon
    copy:
      src: files/firefox-vpn.png
      dest: /home/neil/.local/share/applications/firefox-vpn.png
      owner: neil
      group: neil
      
  - name: copy firefox vpn desktop file
    copy:
      src: files/firefox-vpn.desktop
      dest: /home/neil/.local/share/applications/firefox-vpn.desktop
      owner: neil
      group: neil
      
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/neil/.bashrc
      owner: neil
      group: neil

  - name: add  ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/argoncoast/ansible_desktop.git 

