---
- hosts: localhost
  connection: local
  become: true

  tasks:
  
  - name: prepare eula for ubuntu-restricted-extras 
    debconf:
      name: ttf-mscorefonts-installer
      question: msttcorefonts/accepted-mscorefonts-eula
      vtype: boolean
      value: true
      
  - name: install packages
    package:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - dconf-editor
        - flatpak
        - mc
        - python3-pip
        - python3-psutil
        - python3-setuptools
        - software-properties-common
        - ubuntu-restricted-extras
        - virtualenv
        - wireguard
        
  - name: Add the flathub flatpak repository remote to the user installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: install flatpak Apps
    flatpak:
      name: 
        - com.bitwarden.desktop
        - com.ultimaker.cura
        - com.discordapp.Discord
        - org.signal.Signal
        - org.videolan.VLC
      state: present
      remote: flathub

  - name: Yaru GTK3 Themes
    flatpak:
      name: 
        - org.gtk.Gtk3theme.Yaru-dark
        - org.gtk.Gtk3theme.Yaru-light
        - org.gtk.Gtk3theme.Yaru-bark
        - org.gtk.Gtk3theme.Yaru-bark-dark
        - org.gtk.Gtk3theme.Yaru-magenta
        - org.gtk.Gtk3theme.Yaru-magenta-dark
        - org.gtk.Gtk3theme.Yaru-olive
        - org.gtk.Gtk3theme.Yaru-olive-dark
        - org.gtk.Gtk3theme.Yaru-prussiangreen
        - org.gtk.Gtk3theme.Yaru-prussiangreen-dark
        - org.gtk.Gtk3theme.Yaru-sage
        - org.gtk.Gtk3theme.Yaru-sage-dark   
## Not yet added to Flatpak - See https://github.com/ubuntu/yaru/issues/3618
## Also relevant? https://askubuntu.com/questions/1403931/how-to-apply-system-theme-to-flatpak-apps-that-use-gtk4
#        - org.gtk.Gtk3theme.Yaru-blue
#        - org.gtk.Gtk3theme.Yaru-blue
#        - org.gtk.Gtk3theme.Yaru-purple
#        - org.gtk.Gtk3theme.Yaru-purple-dark
#        - org.gtk.Gtk3theme.Yaru-red
#        - org.gtk.Gtk3theme.Yaru-red-dark
      state: present
      remote: flathub
  
  - name: Yaru Old GTK3 Themes
    flatpak:   
      name: 
        - org.gtk.Gtk3theme.Yaru-Amber-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Amber-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Aqua/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Aqua-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Aqua-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Aubergine/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Aubergine-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Aubergine-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Blue/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Blue-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Blue-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Brown/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Brown-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Brown-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Cinnamon/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Cinnamon-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Cinnamon-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Deepblue/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Deepblue-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Deepblue-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Green/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Green-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Green-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Grey/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Grey-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Grey-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Lavender/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Lavender-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Lavender-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Orange/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Orange-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Orange-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Pink/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Pink-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Pink-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Purple/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Purple-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Purple-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Red/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Red-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Red-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Teal/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Teal-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Teal-light/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Yellow/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Yellow-dark/x86_64/stable
        - org.gtk.Gtk3theme.Yaru-Yellow-light/x86_64/stable
      state: present
      remote: flathub

  - name: install snap packages
    snap:
      name:
        - authy
        - dbeaver-ce
        - gimp
        - telegram-desktop
        - whatsie
  
  - name: Install classic snap packages
    snap:
      name: "{{ classicsnaps }}"
      classic: yes
    vars:
      classicsnaps:
        - gitkraken

  - name: copy firefox vpn icon
    copy:
      src: files/firefox-vpn.png
      dest: /home/neil/.local/share/applications/firefox-vpn.png
      owner: neil
      group: neil
      
  - name: copy firefox vpn desktop file
    copy:
      src: files/firefox-vpn.desktop
      dest: /home/neil/.local/share/applications/firefox-vpn.desktop
      owner: neil
      group: neil
      
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: neil
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/neil/.bashrc
      owner: neil
      group: neil

  - name: add  ansible user
    user:
      name: ansible
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/argoncoast/ansible_desktop.git 
      

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu kinetic stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Install Docker Module for Python
    pip:
      name: docker
