---
- hosts: localhost
  connection: local
  become: true

  tasks:
  
  - name: Remove firefox snap
    snap:
      name: firefox
      state: absent

  - name: Remove Firefox "deb"
    apt:
      name:
        - firefox
      state: absent
      
  - name: Add Firefox Repository
    apt_repository:
      repo: ppa:mozillateam/ppa
      state: present

  - name: Set PPA to be higher priority
    shell:
      cmd: "printf 'Package: firefox\nPin: release o=LP-PPA-mozillateam\nPin-Priority: 1500\n' | tee /etc/apt/preferences.d/mozilla-firefox"

  - name: Update apt and install Firefox
    apt:
      name:
        - firefox
        - fonts-lyx
        - xul-ext-ubufox
      state: latest
      install_recommends: yes
#      force: yes
      update_cache: true
